### ISSUE TITLE
Improve finder matching algorithm

### ISSUE THREAD

**Issue by pguilet** [dakaraphi/eclipse-plugin-commander#21]
Hi,

When it comes to find classes, the finder algorithm is not very good in some case.
For example, if I search "String" well I cannot find it. Class matching exactly the searched expression seems to  not be returned at the top in most cases.

The same for Acronym search. For example the search "IABar" or "IActionBar" to find IActionBar does not return IActionBar whereas it should. The problem seems to be related to capital letters next to others

Am I missing something?

Thanks

**Comment by dakaraphi** [comment]
1) So finder is the same as `open resource`.  It does not search classes.  That would be `open type`.  I have considered adding classes to the `finder` or possibly a separate dialog.

Note, for `finder` by default the matching is across all columns.  Sometimes this can give undesirable results due to partial matching on project or path names.  So you may get better matches by trying `matchtext,` with a comma at the end to enforce only matching file name.

2) Yes currently acronym patterns are built from transitions to upper case.  So continuous capital letters would not match.  So in your example `IB` should match `IActionBar`.
Are you also saying the exact full text "IActionBar" does not match the exact same "IActionBar"?

**Comment by dakaraphi** [comment]
I'm thinking the acronym matching should probably include transitions from upper to lower as well.
So that would produce acronyms like:
IHTTPClient = `IC`
IActionBar = `IAB`

**Comment by pguilet** [comment]
Ok I indeed missed the fact it was open type based finder.
That explains why String and IActionBar was missing from search.

Mixing resources and classes finding could be an interesting feature avoiding using two different menus.
I agree to include transition from upper to lower for better matching. 

Other improvements that comes to my head with current resource base finder would be:

1-Fuzzy or literal search often returns .java and .class files (I have a lot of classes in my workspace). It would be nice to be able to tell to the finder don't show me this kind of files maybe with some preference allowing to give file extension to ignore. Indeed since it does not search across all classes I never will search resources .java or .class so it is just a lot of noise for me. Another solution would be to give those low matching priority.

Also if you would integrate classes search in the same menu, it would be nice to have a shortcut allowing to activate or not the classes search. For example I could use verr maj that I never used and that is easily triggered like tab. I think this would work nicely.

Anyway nice job.

Regards,

Pierre

**Comment by dakaraphi** [comment]
@pguilet I'm not sure why you have `.class` matches.  Normally these are hidden by Eclipse from the list of resources.  I do not have any `.class` matches even though I have classes in my workspace.  I assume this must be due to your workspace configuration related to build output directories.
